### ISSUE TITLE
already a darcula-theme

### ISSUE THREAD

**Issue by fommil** [fourier/idea-darkula-theme#4]
Hi, I wrote https://melpa.org/#/darcula-theme and I was just wondering why you created this duplicate package instead of contributing to the existing one? Perhaps we should merge our efforts and decommission your variant from melpa.

**Comment by fourier** [comment]
Hi,
I didn't know this was existing when I wrote mine, but I don't recall searching. I mainly implemented it as a reflection of my borland cpp theme: https://github.com/fourier/borland-blue-theme with the coverage of the faces which I use (not someone else are using).
Also there are things in darkula-theme which make it not direct 1-to-1 match original IntelliJ Darkula theme - for example they have changed xml coloring for something what I didn't like, so I would rather say this theme is IntelliJ Darkula inspired theme. For other things like GNUS there are no direct match in IDEA at all.
Also I believe the theme choice as a color choice is a personal one. 
Why it is in melpa ? If I've implemented something I feel obliged to share it, that is it. There are other my packages which share functionality of another ones, but if somebody prefers mine, why not to share?

I've also implemented the similar theme for LispWorks (to the extent where it is possible to implement theme there).

**Comment by fommil** [comment]
since we colouring different faces, it would be good to merge them at some point as many of our choices are compatible. I made most choices to match what IntelliJ does for Java/Scala.

**Comment by fommil** [comment]
btw, I also have a "default intellij" theme for bright days

**Comment by ghost** [comment]
Hi, I'm adding my comments just in case you find them useful. I have tried both themes and both are awesome, but so far my favorite is `idea-darkula` mainly because the use of italics and the face for searching.

idea-darkula:
![screen shot 2017-03-08 at 10 02 56](https://cloud.githubusercontent.com/assets/83847/23697151/e4392706-03e6-11e7-848c-c523e57833a0.png)

darcula:
![screen shot 2017-03-08 at 10 03 09](https://cloud.githubusercontent.com/assets/83847/23697154/e730a6d2-03e6-11e7-987d-af78ee628c1c.png)

If I had the same colors from `darcula` but with the italics and search face from `idea-darkula` I would be complete 😄 

Thanks!

**Comment by fommil** [comment]
@anler that's what personal preferences are for...

**Comment by ghost** [comment]
@fommil totally, as I said, that's just my opinion in case you find it useful...

**Comment by fommil** [comment]
@anler no, I mean **literally** you can do exactly what you want by starting with `darcula` and overriding with personal preferences. There is a section in the emacs manual about this if I recall (for themes).

**Comment by ghost** [comment]
@fommil Oh I see what you mean, sorry for the misunderstanding 😞 I moved my lazy butt to do what you said and here's how it looks like 🙂

![image](https://cloud.githubusercontent.com/assets/83847/23702215/9cbb9620-03fa-11e7-80ac-fb0f73b17a65.png)


As you said probably there's a better way using `customize` but since from time to time I declare `custom.el` bankruptcy I prefer to do it this way.

**Comment by fourier** [comment]
The colors in my theme were taken literally by pixel from original Idea screenshot. That is why they are like this. But as I've said, there are still deviations from the original darkula theme in Intellij. For instance the XML colors were based on old IDEA (v14), and I don't want to change them to the current since I like old colors more.
So this theme is not *really* the IDEA's Darkula theme, but rather my adaptation of it to the modes I'm using.
